version: '3'

includes:
  common: ./build/Taskfile.yml
  windows: ./build/windows/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml
  linux: ./build/linux/Taskfile.yml
  ios: ./build/ios/Taskfile.yml
  android: ./build/android/Taskfile.yml

vars:
  APP_NAME: "duckySigner"
  BIN_DIR: "bin"
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9245}}'

tasks:
  build:
    summary: Builds the application
    cmds:
      - task: "{{OS}}:build"
        vars:
          CGO_ENABLED: 1

  build:prod:
    summary: Builds the application for production
    cmds:
      - task: "{{OS}}:build"
        vars:
          PRODUCTION: "true"
          CGO_ENABLED: 1

  package:
    summary: Packages a production build of the application
    cmds:
      - task: "{{OS}}:package"

  run:
    summary: Runs the application
    cmds:
      - task: "{{OS}}:run"

  dev:
    summary: Runs the application in development mode
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}

  setup:docker:
    summary: Builds Docker image for cross-compilation (~800MB download)
    cmds:
      - task: common:setup:docker

# ---------------------- test ----------------------- #

  test:
    summary: Run backend all tests once
    deps:
      - task: common:go:mod:tidy
    cmds:
      - go run github.com/onsi/ginkgo/v2/ginkgo -r -p --trace
      # - go run github.com/onsi/ginkgo/v2/ginkgo -r -p --race --trace

  test:all:
    summary: Runs all tests once
    cmds:
      - task: test
      - task: test:frontend

  test:watch:
    summary: Runs backend Go tests in watch mode
    deps:
      - task: common:go:mod:tidy
    cmds:
      - go run github.com/onsi/ginkgo/v2/ginkgo watch -r -p --trace --output-interceptor-mode=none
      # - go run github.com/onsi/ginkgo/v2/ginkgo watch -r -p --race --trace --output-interceptor-mode=none

  test:frontend:
    summary: Runs the frontend tests once
    dir: frontend
    deps:
      - task: common:install:frontend:deps
    cmds:
      - yarn test

  test:ci:
    summary: Runs all tests for a continuous integration (CI) environment
    deps:
      - task: common:go:mod:tidy
    cmds:
      - go run github.com/onsi/ginkgo/v2/ginkgo -r --procs=6 --compilers=6 --randomize-all --randomize-suites --fail-on-pending --keep-going --race --trace --poll-progress-after=120s --poll-progress-interval=30s
      - task: test:frontend
