"""Ducky Connect SDK.

A collection of utilities and classes for connecting to DApp Connect server for
DuckySigner wallet.
"""

import datetime
from collections.abc import Callable
from dataclasses import dataclass

from algosdk import transaction

# The default base URL to the wallet connect server
DEFAULT_SERVER_BASE_URL = 'http://localhost:1323'
# The default file path to the where information of an established session is stored
DEFAULT_SESSION_FILE_PATH = './.dc_session_info'

# The endpoint path for initializing a session
SESSION_INIT_ENDPOINT = '/session/init'
# The endpoint path for confirming an initialized session
SESSION_CONFIRM_ENDPOINT = '/session/confirm'
# The endpoint path for signing a transaction
SIGN_TXN_ENDPOINT = '/transaction/sign'

@dataclass
class DappInfo:
    """Information about the dApp trying to connect to the wallet.

    It should be information about the app using this library.

    Properties:
        name -- Name of the dApp
        url -- URL for the dApp (default: {''})
        desc -- Description of the dApp. Usually as short explanation that is \
                shown to the user. (default: {''})
        icon -- Icon for the dApp as a data URI for an image (JPEG, PNG or SVG) \
                (default: {''})
    """

    name: str
    url = ''
    desc = ''
    icon = ''

@dataclass
class SessionInfo:
    """Information about an established session.

    Properties:
        id -- Session ID assigned by the connect server and given to this app (client).\
              It is needed to make authenticated requests to the connect server.
        exp -- Date and time this session expires
        addrs -- Addresses of the accounts connected in this session. Typically, these \
                 are the addresses that are allowed to sign things within this session.
    """

    id: str
    exp: datetime.datetime
    addrs: tuple[str]

@dataclass
class __SessionConfirmationInfo:
    """Information needed for an initialized session to be confirmed.

    Properties:
        id -- Confirmation ID assigned by the connect server and given to this app \
              (client)
        code -- The confirmation code the user needs to manually enter into the wallet \
                to approve the dapp's connection to the wallet when confirming the \
                session
        token -- A token generated by the server and given to this app (client). It is \
                 needed to confirm the session.
        exp -- The date and time this session confirmation expires
    """

    id: str
    code: str
    token: str
    exp: datetime.datetime

@dataclass
class StoredSessionInfo:
    """Information regarding a session that is to be stored into a file.

    Properties:
        connect_id -- Base64-encoded Elliptic-curve Diffie-Hellman (ECDH) public key \
                      that is to be used to identify the dApp to the DApp Connect \
                      Server. It is referred to as the "dApp ID" in some other \
                      documentation. More than one session may use the same connect \
                      ID/key.
        session -- Information about the session
        dapp -- Information about the dapp this session is for
        server_url -- Connect server URL. If not set, the default (localhost:1323) is \
                      used. (default: {DEFAULT_SERVER_BASE_URL})
        file_path -- Path to the file that contains the information for the \
                     established session
    """

    connect_id: str
    session: SessionInfo
    dapp: DappInfo
    server_url = DEFAULT_SERVER_BASE_URL
    file_path = DEFAULT_SESSION_FILE_PATH

@dataclass
class ConnectOptions:
    """Options for connecting to DuckySigner.

    Properties:
        dapp -- Information about the dApp connecting to the wallet
        server_url -- Base URL to the wallet's connect server \
                      (default: {DEFAULT_SERVER_BASE_URL})
        session_file_path -- Path to the file that contains the information for the \
                             established session
        confirm_code_display_fn -- Function for displaying the confirmation code
    """

    dapp: DappInfo
    server_url = DEFAULT_SERVER_BASE_URL
    session_file_path = DEFAULT_SESSION_FILE_PATH
    confirm_code_display_fn: Callable[[str], None]

class DuckyConnect:
    """Class for connecting to and interacting with a DApp Connect server."""

    __dappInfo: DappInfo
    __server_url: str
    __session_file: str
    __confirm_code_display_fn: Callable[[str], None]


    def __init__(options: ConnectOptions):
        """Initialize the class with the given connection options.

        Arguments:
            options -- Options for connecting to the DApp Connect Server
        """
        pass

    def establish_session() -> SessionInfo:
        """Create a new dApp connect session.

        The new DApp Connect session can then be used for other actions (e.g. signing a
        transaction)

        Returns:
            Information about the newly confirmed (established) session
        """
        pass

    def __initialize_session() -> __SessionConfirmationInfo:
        """Create and initialize a new session with the dApp connect server.

        Returns:
            Information needed to confirm the newly initialized session
        """
        pass

    def __confirm_session(session_confirm: __SessionConfirmationInfo) -> SessionInfo:
        """Confirm an initialized session.

        Confirming the initialized session completes the establishment of the session
        with the dApp connect server. After the session is confirmed, it becomes an
        established session.

        Arguments:
            session_confirm -- Confirmation information about the initialized session. \
                               Should be what is returned by the \
                               `__initialize_session()` method.

        Returns:
            Information about the current established session being used.
        """
        pass

    def retrieve_session() -> StoredSessionInfo:
        """Retrieve session data from local storage.

        Returns:
            The information about the session stored locally.
        """
        pass

    def end_session() -> None:
        """End the current established session.

        Ends the current established session by contacting the server, if possible. If
        the server cannot end the session, the stored session information is removed
        anyway.
        """
        pass

    def __store_session(session_info: SessionInfo) -> None:
        """Store the given session information into the session file.

        If a session file exists, it is overwritten with the given session information.

        Arguments:
            session_info -- Session information to store
        """
        pass

    def __remove_stored_session() -> None:
        """Remove the stored session information."""
        pass

    def __store_connect_key(key: str = '') -> None:
        """Store (and maybe generate) connect key.

        Securely store the given Base64-encoded Elliptic-curve Diffie-Hellman (ECDH)
        secret key ("connect key") that is to be used to identify the dApp to the DApp
        Connect server. A connect key is required to create and use a session. The
        connect key may be referred to as the "dApp key" in other documentation.

        Keyword Arguments:
            key -- Base64-encoded ECDH secret key for the dApp to store. If no key is \
                   given, one is generated. (default: {''})
        """
        pass

    def __retrieve_connect_key() -> str:
        """Get the connect key from secure storage.

        Returns:
            Base64-encoded connect key
        """
        pass

    def __remove_connect_key() -> None:
        """Remove the connect key from secure storage."""
        pass

    def sign_transaction(txn: transaction.Transaction, signer_addr: str = ''):
        """Sign the given transaction.

        Arguments:
            txn -- Transaction to be signed

        Keyword Arguments:
            signer_addr -- Optional signer address, if it is not the sender of the \
                           transaction (default: {''})
        """
        pass
