import algosdk from 'algosdk'

/** The default base URL to the wallet connect server */
export const DEFAULT_SERVER_BASE_URL = 'http://localhost:1323'
/** The endpoint path for initializing a session */
export const SESSION_INIT_ENDPOINT = '/session/init'
/** The endpoint path for confirming an initialized session */
export const SESSION_CONFIRM_ENDPOINT = '/session/confirm'
/** The endpoint path for signing a transaction */
export const SIGN_TXN_ENDPOINT = '/transaction/sign'

/** Information about the dApp trying to connect to the wallet. It should be the app using this
 * library.
 */
export interface DappInfo {
  /** Name of the dApp */
  name: string
  /** URL for the dApp */
  url?: string
  /** Description of the dApp. Usually as short explanation that is shown to the user. */
  desc?: string
  /** Icon for the dApp as a data URI for an image (JPEG, PNG or SVG) */
  icon?: string
}

/** Information about an established session */
export interface SessionInfo {
  /** Session ID assigned by the connect server and given to this app (client). It is needed to make
   * authenticated requests to the connect server.
   */
  id: string
  /** The date and time this session expires */
  exp: Date
  /** The addresses of the accounts connected in this session. Typically, these are the addresses
   * that are allowed to sign things within this session.
   */
  addrs: string[]
}

/** Information needed for an initialized session to be confirmed, and therefore established */
interface SessionConfirmationInfo {
  /** Confirmation ID assigned by the connect server and given to this app (client) */
  id: string
  /** The confirmation code the user needs to manually enter into the wallet to approve the dapp's
   * connection to the wallet when confirming the session
   */
  code: string
  /** A token generated by the server and given to this app (client). It is needed to confirm the
   * session.
   */
  token: string
  /** The date and time this session confirmation expires */
  exp: Date
}

/** Information regarding a session that is to be stored into local storage */
export interface StoredSessionInfo extends SessionInfo {
  /** Information about the dapp this session is for */
  dapp: DappInfo
  /** The connect server URL. If not set, the default (localhost:1323) is used. */
  serverURL?: string
}

export interface ConnectOptions {
  /** Information about the dApp connecting to the wallet */
  dapp: DappInfo
  /** The base URL to the wallet's connect server */
  serverBaseURL?: string
  /** Function for displaying the confirmation code */
  confirmCodeDisplayFn?: (code: string) => void
}

/** Class for connecting to and interacting with a DuckySigner DApp Connect server */
export class DuckyConnect {
  #baseURL: string
  #dappInfo: DappInfo
  #confirmCodeDisplayFn: (code: string) => void

  constructor(options: ConnectOptions) {
    this.#baseURL = options.serverBaseURL ?? DEFAULT_SERVER_BASE_URL
    this.#dappInfo = options.dapp
    this.#confirmCodeDisplayFn = options.confirmCodeDisplayFn ?? ((code: string) => alert(`Confirmation code: ${code}`))
  }

  /** Create a new dApp connect session that can then be used for other actions (e.g. signing a transaction) */
  async establishSession() {
    let confirmData = await this.#initializeSession()
    let sessionData = await this.#confirmSession(confirmData)
    this.#storeSession(sessionData)
    return sessionData
  }

  /** Create and initialize a new session with the dApp connect server */
  async #initializeSession(): Promise<SessionConfirmationInfo> {
    // TODO: Generate dApp ID and key & store key

    // TODO: Make request to server
      // On error: Log error and return

    // TODO: Return session confirmation data
    return {id: '', code: '', token: '', exp: new Date}
  }

  /** Confirm an initialized session to complete the establishment of the session with the dApp connect server */
  async #confirmSession(sessionConfirm: SessionConfirmationInfo): Promise<SessionInfo> {
    // TODO: Make request to server
      // On error: Log error and return

    // TODO: Get confirmation code and display code (default with an alert box)
      // On error: Log error and return

    // TODO: Return new established session data
    return {id: '', exp: new Date, addrs: []}
  }

  /** Retrieve session data from local storage */
  retrieveSessionData(): StoredSessionInfo|null {
    // TODO
    return {id: '', exp: new Date, addrs: [], dapp: {name: ''}}
  }

  /** End the current established session by contacting the server, if possible */
  async endSession() {
    // TODO
  }

  /** Securely store the given session data into local storage */
  #storeSession(sessionData: SessionInfo) {
    // TODO
  }

  /** Remove all session data from local storage */
  #removeStoredSession() {
    // TODO
  }

  /** Sign the given transaction */
  async signTransaction(txn: algosdk.Transaction, signerAddr?: string) {
    // TODO
    return algosdk.decodeSignedTransaction(new Uint8Array)
  }

}
