name: Publish DApp Connect API Specification
on:
  push:
    branches:
      - master
    paths:
      - docs/dapp-connect-api/**
      - .github/workflows/**
permissions:
  contents: write
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate OpenAPI definition
        uses: swaggerexpert/apidom-validate@v1
        with:
          definition-file: docs/dapp-connect-api/openapi.yml
          fails-on: 2
      - name: Build Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: docs/dapp-connect-api/openapi.yml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: swagger-ui
          target-folder: dapp-connect-api
